In [1]:
import pandas as pd

## 1. Exploration `survey.csv`

Includes one row per participant (49 total) and 23 columns with the following fields:
- Demographic and lifestyle factors.
- Clinical questionaires (insomnia, depression and anxiety) before, mid and after experiment. Also MEQ questionnaire.

In [2]:
survey_df = pd.read_csv("data/survey.csv")

print(f"Shape: {survey_df.shape[0]} rows x {survey_df.shape[1]} columns")
survey_df.head()

Shape: 49 rows x 23 columns

,deviceId,sex,age,marriage,occupation,smartwatch,regular,exercise,coffee,smoking,...,ISI_1,PHQ9_1,GAD7_1,MEQ,ISI_2,PHQ9_2,GAD7_2,ISI_F,PHQ9_F,GAD7_F
0,pm96,1,36,1,3,1,3,5,4,1,...,8,1,1,46,7.0,1.0,0.0,9.0,0.0,0.0
1,vc10,2,31,1,3,2,2,5,2,1,...,11,3,1,28,17.0,4.0,0.0,8.0,1.0,0.0
2,pg18,2,38,1,3,1,3,3,3,1,...,10,5,2,48,12.0,3.0,1.0,10.0,5.0,4.0
3,nd56,2,40,3,2,1,4,4,5,1,...,8,3,0,55,10.0,6.0,0.0,9.0,4.0,0.0
4,vs14,2,28,1,2,2,4,2,2,1,...,14,10,8,35,14.0,12.0,11.0,13.0,11.0,6.0

## 2. Exploration `sensor_hrv_filtered.csv`

Contains sensor and HRV measurements in 5-minute intervals (from `ts_start` to `ts_end`, both in miliseconds).
- Sensor information (smartwatch) aggregated using the mean value for the time interval
- HRV measurments. Computed from PPG data.
`sensor_hrv` can be ignored, since it is esentially the same data with no quality threshold.

In [3]:
sensor_hrv_df = pd.read_csv("data/sensor_hrv_filtered.csv")

print(f"Shape: {sensor_hrv_df.shape[0]} rows x {sensor_hrv_df.shape[1]} columns")
sensor_hrv_df.head()

Shape: 38913 rows x 28 columns

,deviceId,ts_start,ts_end,missingness_score,HR,ibi,acc_x_avg,acc_y_avg,acc_z_avg,grv_x_avg,...,calories,light_avg,sdnn,sdsd,rmssd,pnn20,pnn50,lf,hf,lf/hf
0,ab60,1617262425031,1617262724833,0.295448,84.592816,728.534374,0.284765,-0.593973,9.195984,-0.094203,...,0.000000,841.324415,89.363225,78.033038,98.417649,0.746269,0.391791,1818.065625,1252.992443,1.450979
1,ab60,1616736817151,1616737116986,0.239085,78.589565,781.896913,3.050179,-1.239353,5.790543,-0.211973,...,0.085083,486.485050,100.804974,73.468687,106.602933,0.803704,0.540741,1918.499169,2784.393293,0.689019
2,ab60,1616736517083,1616736816952,0.100773,75.620524,812.183910,2.153267,-3.546833,8.499866,-0.628970,...,NaN,779.033113,89.073518,48.675496,74.504896,0.809816,0.484663,1292.696555,1034.550027,1.249525
3,ab60,1616736217077,1616736516883,0.268178,85.813165,769.754943,2.898409,-3.401356,4.606113,-0.249247,...,1.375000,389.408638,102.371770,48.631219,70.615187,0.719178,0.400685,1561.785747,812.118619,1.923101
4,ab60,1616734416800,1616734716672,0.043466,76.944500,775.190053,-0.050221,-6.576164,5.377019,0.715893,...,0.000000,276.345515,84.045665,42.104491,66.973170,0.736111,0.450000,3460.217895,1886.157661,1.834533

## 3. Exploration `sleep_diary.csv`

Self reported participant sleep schedules from daily surveys. In-bed duration, sleep duration, WASO, sleep efficiency and sleep latency.

In [4]:
sleep_diary_df = pd.read_csv("data/sleep_diary.csv")

print(f"Shape: {sleep_diary_df.shape[0]} rows x {sleep_diary_df.shape[1]} columns")
sleep_diary_df.head()

Shape: 1372 rows x 11 columns

,userId,date,go2bed,asleep,wakeup,wakeup@night,waso,sleep_duration,in_bed_duration,sleep_latency,sleep_efficiency
0,pm96,2021-03-09,01:00:00,02:00:00,08:30:00,0,0.0,6.500000,7.500000,1.000000,0.866667
1,pm96,2021-03-10,00:00:00,00:40:00,07:50:00,0,0.0,7.166667,7.833333,0.666667,0.914894
2,pm96,2021-03-11,00:30:00,01:00:00,07:40:00,0,0.0,6.666667,7.166667,0.500000,0.930233
3,pm96,2021-03-12,00:30:00,01:00:00,07:50:00,0,0.0,6.833333,7.333333,0.500000,0.931818
4,pm96,2021-03-13,01:00:00,01:30:00,10:30:00,0,0.0,9.000000,9.500000,0.500000,0.947368

In [5]:
sleep_counts = sleep_diary_df["userId"].value_counts().sort_values(ascending=False)
# should be 28 entries per user, since it is 1 daily entry
print(f"\nUsers: {sleep_counts.shape[0]}, min={sleep_counts.min()}, max={sleep_counts.max()}")

Users: 49, min=28, max=28